setting:
    sandbox         : true
    security_plugin : 0
    request_log     : false
    sql_log         : false
    timezone        : UTC
    cache_time      : 600
    secret_key      : gqD8iM6pjJ
    app_id          : boss

db_data:
    adapter     : Mysql
    host        : 127.0.0.1
    port        : 3306
    username    : root
    password    : root
    dbname      : v3-boss
    charset     : utf8mb4

db_trade:
    adapter     : Mysql
    host        : 127.0.0.1
    port        : 3306
    username    : root
    password    : root
    dbname      : v3-trade
    charset     : utf8mb4

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

mq:
    host        :
    port        :
    username    :
    password    :
    vhost       :

sso:
    base_url    : https://top.gamehetu.com/api/sso/
    api_url     : https://top.gamehetu.com/api/synchro
    sessionlog_url : https://top.gamehetu.com/api/sessionlog

api:
  # soap yar http
  rpc_protocol  : http
  rpc_host      : http://v3-rpc.com